# Generated by Django 6.1.1 on 2026-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instanceruleconfig',
            name='unique_instance_rule',
        ),
        migrations.AddField(
            model_name='instanceruleconfig',
            name='clinical_system',
            field=models.CharField(choices=[('emis', 'EMIS Web'), ('systm_one', 'SystmOne')], db_index=True, default='emis', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='instanceruleconfig',
            constraint=models.UniqueConstraint(fields=('instance', 'rule', 'clinical_system'), name='unique_instance_rule_system'),
        ),
    ]
