# Generated by Django 6.1.1 on 2026-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_disabled',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Enabled'), (1, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='instanceruleconfig',
            name='system_type',
            field=models.CharField(blank=True, choices=[('systemone', 'System One'), ('emis', 'Emis')], max_length=16, null=True),
        ),
    ]
