# Generated by Django 6.1.1 on 2026-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='organisation_type',
            field=models.CharField(blank=True, default='GP Practice', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='sra_account',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='vm',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='clinical_system',
            field=models.CharField(blank=True, default='EMIS', max_length=64),
        ),
    ]
