# Generated by Django 6.1.1 on 2026-09-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0002_rule_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='is_disabled',
            field=models.CharField(choices=[('N', 'None'), ('S', 'System1'), ('E', 'Emis'), ('B', 'Both')], default='N', max_length=1),
        ),
    ]
