# Generated by Django 6.1.1 on 2026-09-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0002_client_code_client_organisation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clinical_system',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='organisation_type',
        ),
    ]
