# Generated by Django 6.1.1 on 2026-09-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_onboarding', '0004_alter_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sra_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vm',
        ),
    ]
